### ISSUE TITLE
Question about scale of testing

### ISSUE THREAD

**Issue by Jerryme-xxm** [ryuz/BinaryBrain#3]
Thanks for your great work!

You train the network based on MNIST 28*28,  and test the network on camera image 640*132,  using slide window like Yolo.
I find that there are always 4 digits per column.
![digits](https://user-images.githubusercontent.com/58944064/163337826-7ee646ef-9873-4967-bafe-921c27a974dc.png)

May I ask if every digit of camera must be about 28*28, which means that digit scale of training and testing must be the same?
If so, what about adding multi-scale function refer to Yolo3?

**Comment by ryuz** [comment]
Thank you for your comment.
In the semantic segmentation example, the input and output are the same size.

https://github.com/ryuz/BinaryBrain/blob/master/samples/python/mnist/MnistSegmentationAndClassification.ipynb

The training data needs to be expanded in order to learn the parts of the image where the numbers are not centered.

**Comment by Jerryme-xxm** [comment]
Thanks for your convenient time.

I think this step maybe a little similar to this method.
![MNIST](https://user-images.githubusercontent.com/58944064/163375054-15063cac-2d3a-4836-ab5f-990f027c5521.png)

**Comment by ryuz** [comment]
Thanks for the information.
Data Augmentation is very important as well, even for binary networks.
I think it is important to perform appropriate data augmentation for the purpose.
